// components/socials.jsx
import { FaGithub, FaPatreon, FaTwitter, FaVk } from 'react-icons/fa'

import OuterLink from './outerLink'

export default function Socials() {
  return (
    <div className="flex flex-wrap content-center mx-auto mt-10 mb-2 md:my-0 md:mx-4">
      <OuterLink name="VKontakte" href="https://vk.com/thefluffies">
        <FaVk className="mx-2 w-7 h-7 hover:text-blue-500 transition-colors duration-300" />
      </OuterLink>

      <OuterLink name="Twitter" href="https://twitter.com/TFluffies">
        <FaTwitter className="mx-2 w-7 h-7 hover:text-blue-400 transition-colors duration-300" />
      </OuterLink>

      <OuterLink name="Patreon" href="https://www.patreon.com/the_fluffies">
        <FaPatreon className="mx-2 w-7 h-7 hover:text-red-400 transition-colors duration-300" />
      </OuterLink>

      <OuterLink
        name="GitHub"
        href="https://github.com/Electrum18/The-Fluffies"
      >
        <FaGithub className="mx-2 w-7 h-7 hover:text-gray-500 transition-colors duration-300" />
      </OuterLink>
    </div>
  )
}

export function SocialsMini() {
  return (
    <div className="flex flex-wrap content-center">
      <OuterLink name="VKontakte" href="https://vk.com/thefluffies">
        <FaVk className="w-5 h-5 mx-2 hover:text-blue-500 transition-colors duration-300" />
      </OuterLink>

      <OuterLink name="Twitter" href="https://twitter.com/TFluffies">
        <FaTwitter className="w-5 h-5 mx-2 hover:text-blue-400 transition-colors duration-300" />
      </OuterLink>

      <OuterLink name="Patreon" href="https://www.patreon.com/the_fluffies">
        <FaPatreon className="w-5 h-5 mx-2 hover:text-red-400 transition-colors duration-300" />
      </OuterLink>

      <OuterLink
        name="GitHub"
        href="https://github.com/Electrum18/The-Fluffies"
      >
        <FaGithub className="w-5 h-5 mx-2 hover:text-gray-500 transition-colors duration-300" />
      </OuterLink>
    </div>
  )
}

// components/Socials.vue
<template lang="pug">
  v-row.socials.my-n9(justify="center")
    v-btn.ma-4(
      icon
      large
      target="_blank"
      title="Github"
      href="https://github.com/Electrum18/The-Fluffies"
      rel="noopener"
      aria-label="Github"
    )
      v-icon(large) {{ icons.mdiGithub }}

    v-btn.ma-4(
      icon
      large
      target="_blank"
      title="Twitter"
      href="https://twitter.com/TFluffies"
      rel="noopener"
      aria-label="Twitter"
    )
      v-icon(large) {{ icons.mdiTwitter }}

    v-btn.ma-4(
      icon
      large
      target="_blank"
      title="Patreon"
      href="https://www.patreon.com/the_fluffies"
      rel="noopener"
      aria-label="Patreon"
    )
      v-icon(large) {{ icons.mdiPatreon }}
</template>

<script lang="ts">
import { reactive } from '@vue/composition-api'

import { mdiGithub, mdiPatreon, mdiTwitter } from '@mdi/js'

export default {
  setup() {
    const icons = reactive({
      mdiGithub,
      mdiPatreon,
      mdiTwitter
    })

    return {
      icons
    }
  }
}
</script>

<style lang="sass">
.socials.row
  flex: unset
  margin: 0
  overflow: hidden
</style>
